"""Added the status column to the payment

Revision ID: 80f96899227e
Revises: 28016a291046
Create Date: 2024-10-06 09:50:04.998742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f96899227e'
down_revision: Union[str, None] = '28016a291046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('staus', sa.Enum('SUCCESS', 'PENDING', 'FAILED', 'PROCESSING', name='paymentstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'staus')
    # ### end Alembic commands ###
